### ISSUE TITLE
npm에 올려주실 수 있나요?

### ISSUE THREAD

**Issue by namse** [devdoomari/react-daum-map#1]
NPM에 올려져 있으면 다양한 곳에서 쉽게 사용할 수 있어보이는 프로젝트로 보이는데, 혹시 NPM에 올려주실 수 있으신가요?

**Comment by devdoomari** [comment]
의견은 좋으시지만 아직 production 레벨에서 쓸만할 것이 못될껍니다ㅠㅜ 
궂이 쓰시고 싶으시면 npm 에서

``` bash
npm install git+ssh://git@github.com:devdoomari/react-daum-map
```

으로 하시면 되지만
될 수 있으면 react-leaflet 같은걸 쓰시는것도 괜찮을것 같습니다 :)
https://github.com/PaulLeCam/react-leaflet

**Comment by namse** [comment]
@devdoomari 혹시 괜찮으시다면 제가 이 프로젝트를 정리해서 npm에 올려 사용해도 괜찮을까요?
